### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by robinyoublind** [peasee/poll#1]
I added my keys from Cloudflare and Captcha and ran the installer script. I also tried running through the manual steps. In both instances, navigating to the site just displays "Cannot GET /".

**Comment by volkux** [comment]
I have the same issue

**Comment by diinnk** [comment]
I believe this is because you are navigating to the IP and port of the Node instance running on your machine, not the 443 port exposed by nginx. Use that port instead and it'll route as expected

**Comment by peasee** [comment]
Sorry for missing this! My issue notifications for this repo weren't setup properly 😮‍💨 I'm currently working on a re-developed backend, as well as deployments with Docker and a compose file. I've opened a draft PR so you can track the work, if you're interested: https://github.com/peasee/poll/pull/2

Hopefully it will make deployment issues like these easier, and give you more control in the way you do your deployments - even running it without HTTPS if that's your jam (not that I'd recommend it).
